// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitecData;

namespace VitecData.Migrations
{
    [DbContext(typeof(VitecContext))]
    partial class VitecContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VitecData.Models.Card", b =>
                {
                    b.Property<long>("cardID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpDate");

                    b.Property<int>("SecurityNumbers");

                    b.HasKey("cardID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("VitecData.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("VitecData.Models.Subscription", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("BillingFrequency");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int?>("ProductID");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("VitecData.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("HashedPassword");

                    b.Property<string>("LastName");

                    b.Property<int>("PhoneNumber");

                    b.Property<string>("Salt");

                    b.Property<string>("UserName");

                    b.Property<int?>("ZIP1");

                    b.HasKey("ID");

                    b.HasIndex("ZIP1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VitecData.Models.UserCards", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UserID");

                    b.Property<long?>("cardID");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("cardID");

                    b.ToTable("UserCards");
                });

            modelBuilder.Entity("VitecData.Models.UserSubscriptions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AutomaticBilling");

                    b.Property<DateTime>("ExpDate");

                    b.Property<DateTime>("SignUpDate");

                    b.Property<int?>("SubscriptionID");

                    b.Property<int?>("UserID");

                    b.HasKey("ID");

                    b.HasIndex("SubscriptionID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("VitecData.Models.ZipCity", b =>
                {
                    b.Property<int>("ZIP")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName");

                    b.HasKey("ZIP");

                    b.ToTable("ZipCities");
                });

            modelBuilder.Entity("VitecData.Models.Subscription", b =>
                {
                    b.HasOne("VitecData.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("VitecData.Models.User", b =>
                {
                    b.HasOne("VitecData.Models.ZipCity", "ZIP")
                        .WithMany()
                        .HasForeignKey("ZIP1");
                });

            modelBuilder.Entity("VitecData.Models.UserCards", b =>
                {
                    b.HasOne("VitecData.Models.User", "User")
                        .WithMany("UserCards")
                        .HasForeignKey("UserID");

                    b.HasOne("VitecData.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("cardID");
                });

            modelBuilder.Entity("VitecData.Models.UserSubscriptions", b =>
                {
                    b.HasOne("VitecData.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionID");

                    b.HasOne("VitecData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
